client_config_backend: settings
client_config:
  client_id: 372023844266-mamjg4gct5k31t4l3rmlem4e2gc02fus.apps.googleusercontent.com
  client_secret: ogL5YBFGaY-RaSiYDQfzYje-

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install